spring:
  application:
    name: rag-profile-practice

  ai:
    openai:
      api-key: ${SPRING_AI_OPENAI_API_KEY}// 필요할 때 넣어서 실행하기
    vectorstore:
      chroma:
        client:
          host: http://localhost
          port: 8000
        initialize-schema: true
        collection-name: SpringCollection